export const SET_USER_REQUEST = "SET_USER_REQUEST";
export const SET_USER_SUCCESS = "SET_USER_SUCCESS";
export const SET_USER_FAILURE = "SET_USER_FAILURE";

export const SET_USER_SIGNUP_REQUEST = "SET_USER_SIGNUP_REQUEST";
export const SET_USER_SIGNUP_SUCCESS = "SET_USER_SIGNUP_SUCCESS";
export const SET_USER_SIGNUP_FAILURE = "SET_USER_SIGNUP_FAILURE";

export const SET_ERRORS = "SET_ERRORS";
export const USER_LOGOUT = "USER_LOGOUT"