export const SET_USER_REQUEST = "SET_USER_REQUEST";
export const SET_USER_SUCCESS = "SET_USER_SUCCESS";
export const SET_USER_FAILURE = "SET_USER_FAILURE";

export const SET_PARTNER_REQUEST = "SET_PARTNER_REQUEST";
export const SET_PARTNER_SUCCESS = "SET_PARTNER_SUCCESS";
export const SET_PARTNER_FAILURE = "SET_PARTNER_FAILURE";

export const SET_USER_SIGNUP_REQUEST = "SET_USER_SIGNUP_REQUEST";
export const SET_USER_SIGNUP_SUCCESS = "SET_USER_SIGNUP_SUCCESS";
export const SET_USER_SIGNUP_FAILURE = "SET_USER_SIGNUP_FAILURE";


export const SET_PARTNER_SIGNUP_REQUEST = "SET_PARTNER_SIGNUP_REQUEST";
export const SET_PARTNER_SIGNUP_SUCCESS = "SET_PARTNER_SIGNUP_SUCCESS";
export const SET_PARTNER_SIGNUP_FAILURE = "SET_PARTNER_SIGNUP_FAILURE";

export const SET_SEARCH_REQUEST = "SET_SEARCH_REQUEST";
export const SET_SEARCH_SUCCESS = "SET_SEARCH_SUCCESS";
export const SET_SEARCH_FAILURE = "SET_SEARCH_FAILURE";


export const SET_USER_PROFILE_REQUEST = "SET_USER_PROFILE_REQUEST";
export const SET_USER_PROFILE_SUCCESS = "SET_USER_PROFILE_SUCCESS";
export const SET_USER_PROFILE_FAILURE = "SET_USER_PROFILE_FAILURE";


export const SET_ERRORS = "SET_ERRORS";
export const USER_LOGOUT = "USER_LOGOUT"
export const PARTNER_LOGOUT = "PARTNER_LOGOUT"